export default ACTION_TYPES = {
  LOGIN: 'LOGIN',
  SET_TOKEN: 'SET_TOKEN',
  SET_LOGGED: 'SET_LOGGED',
  SET_MOVIE: 'SET_MOVIE',
  LOGOUT: 'LOGOUT',

  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
  DELETE_USER: 'DELETE_USER',


};
